// Centralized comprehensive demo and fallback data for local previews and offline modes.

export type DemoUser = {
  id: string;
  email: string;
  full_name: string;
  role: string;
  active: boolean;
  created_at: Date;
  plan: string | null;
  status: string;
  charity_name: string;
  scores: number;
};

export type DemoSub = {
  user_id: string;
  email: string;
  full_name: string;
  plan: string | null;
  status: string;
  price_pence: number;
  renewal_date: string | null;
  updated_at: Date;
};

export type DemoDraw = {
  id: string;
  period: string;
  draw_type: "random" | "algorithmic";
  status: "draft" | "published";
  winning_numbers: number[] | null;
  pool_pence: number;
  jackpot_in_pence: number;
  jackpot_out_pence: number;
  published_at: Date | null;
  created_at: Date;
  entryCount: number;
};

export type DemoWinner = {
  id: string;
  draw_id: string;
  user_id: string;
  tier: number;
  amount_pence: number;
  verification: "pending" | "approved" | "rejected";
  payment_status: "pending" | "paid";
  proof_name: string | null;
  has_proof: boolean;
  created_at: Date;
  period: string;
  full_name: string;
  email: string;
};

export const DEMO_USERS: DemoUser[] = [
  {
    id: "demo-admin-id",
    email: "admin@digitalheroes.test",
    full_name: "Demo Admin",
    role: "admin",
    active: true,
    created_at: new Date("2026-01-10"),
    plan: "yearly",
    status: "active",
    charity_name: "Hope Foundation",
    scores: 5,
  },
  {
    id: "demo-player-id",
    email: "player@digitalheroes.test",
    full_name: "Demo Player 1",
    role: "user",
    active: true,
    created_at: new Date("2026-02-14"),
    plan: "monthly",
    status: "active",
    charity_name: "Green Earth Trust",
    scores: 5,
  },
  {
    id: "demo-user-2",
    email: "player2@digitalheroes.test",
    full_name: "Demo Player 2",
    role: "user",
    active: true,
    created_at: new Date("2026-02-20"),
    plan: "yearly",
    status: "active",
    charity_name: "Green Earth Trust",
    scores: 5,
  },
  {
    id: "demo-user-3",
    email: "aarav.sharma@digitalheroes.test",
    full_name: "Aarav Sharma",
    role: "user",
    active: true,
    created_at: new Date("2026-03-05"),
    plan: "monthly",
    status: "active",
    charity_name: "Shelter Together",
    scores: 5,
  },
  {
    id: "demo-user-4",
    email: "priya.patel@digitalheroes.test",
    full_name: "Priya Patel",
    role: "user",
    active: true,
    created_at: new Date("2026-03-12"),
    plan: "yearly",
    status: "active",
    charity_name: "Girls Into Golf",
    scores: 5,
  },
  {
    id: "demo-user-5",
    email: "rohan.mehta@digitalheroes.test",
    full_name: "Rohan Mehta",
    role: "user",
    active: true,
    created_at: new Date("2026-03-25"),
    plan: "monthly",
    status: "active",
    charity_name: "Wildlife Corridors",
    scores: 5,
  },
  {
    id: "demo-user-6",
    email: "ananya.iyer@digitalheroes.test",
    full_name: "Ananya Iyer",
    role: "user",
    active: true,
    created_at: new Date("2026-04-02"),
    plan: "monthly",
    status: "active",
    charity_name: "Mind & Body Wellness",
    scores: 5,
  },
  {
    id: "demo-user-7",
    email: "vikram.singh@digitalheroes.test",
    full_name: "Vikram Singh",
    role: "user",
    active: true,
    created_at: new Date("2026-04-18"),
    plan: "yearly",
    status: "active",
    charity_name: "Fair Play Sports",
    scores: 5,
  },
  {
    id: "demo-user-8",
    email: "neha.gupta@digitalheroes.test",
    full_name: "Neha Gupta",
    role: "user",
    active: true,
    created_at: new Date("2026-05-01"),
    plan: "monthly",
    status: "active",
    charity_name: "Hope Foundation",
    scores: 5,
  },
  {
    id: "demo-user-9",
    email: "kabir.das@digitalheroes.test",
    full_name: "Kabir Das",
    role: "user",
    active: true,
    created_at: new Date("2026-05-15"),
    plan: "monthly",
    status: "active",
    charity_name: "Neighbourhood Kitchen",
    scores: 5,
  },
  {
    id: "demo-user-10",
    email: "meera.nair@digitalheroes.test",
    full_name: "Meera Nair",
    role: "user",
    active: true,
    created_at: new Date("2026-05-29"),
    plan: "monthly",
    status: "cancelled",
    charity_name: "Mind & Body Wellness",
    scores: 4,
  },
  {
    id: "demo-user-11",
    email: "rajesh.verma@digitalheroes.test",
    full_name: "Rajesh Verma",
    role: "user",
    active: true,
    created_at: new Date("2026-06-10"),
    plan: "monthly",
    status: "past_due",
    charity_name: "Ocean Guardians",
    scores: 5,
  },
  {
    id: "demo-user-12",
    email: "sneha.reddy@digitalheroes.test",
    full_name: "Sneha Reddy",
    role: "user",
    active: true,
    created_at: new Date("2026-06-22"),
    plan: null,
    status: "inactive",
    charity_name: "Little Readers",
    scores: 3,
  },
  {
    id: "demo-user-13",
    email: "arjun.kapoor@digitalheroes.test",
    full_name: "Arjun Kapoor",
    role: "user",
    active: true,
    created_at: new Date("2026-07-04"),
    plan: "monthly",
    status: "active",
    charity_name: "Girls Into Golf",
    scores: 5,
  },
  {
    id: "demo-user-14",
    email: "pooja.joshi@digitalheroes.test",
    full_name: "Pooja Joshi",
    role: "user",
    active: true,
    created_at: new Date("2026-07-19"),
    plan: "yearly",
    status: "active",
    charity_name: "Fair Play Sports",
    scores: 5,
  },
  {
    id: "demo-user-15",
    email: "devendra.rao@digitalheroes.test",
    full_name: "Devendra Rao",
    role: "user",
    active: true,
    created_at: new Date("2026-08-01"),
    plan: "monthly",
    status: "active",
    charity_name: "First Steps Nutrition",
    scores: 5,
  },
  {
    id: "demo-user-16",
    email: "simran.kaur@digitalheroes.test",
    full_name: "Simran Kaur",
    role: "user",
    active: true,
    created_at: new Date("2026-08-11"),
    plan: "monthly",
    status: "active",
    charity_name: "Wildlife Corridors",
    scores: 5,
  },
  {
    id: "demo-user-17",
    email: "tanya.malhotra@digitalheroes.test",
    full_name: "Tanya Malhotra",
    role: "user",
    active: true,
    created_at: new Date("2026-08-20"),
    plan: "yearly",
    status: "active",
    charity_name: "Warm Homes Project",
    scores: 5,
  },
  {
    id: "demo-user-18",
    email: "kunal.sen@digitalheroes.test",
    full_name: "Kunal Sen",
    role: "user",
    active: true,
    created_at: new Date("2026-08-28"),
    plan: "monthly",
    status: "cancelled",
    charity_name: "Night Shelter Network",
    scores: 4,
  },
  {
    id: "demo-user-19",
    email: "deepika.bose@digitalheroes.test",
    full_name: "Deepika Bose",
    role: "user",
    active: true,
    created_at: new Date("2026-09-02"),
    plan: "monthly",
    status: "past_due",
    charity_name: "Girls Into Golf",
    scores: 5,
  },
  {
    id: "demo-user-20",
    email: "manish.choudhary@digitalheroes.test",
    full_name: "Manish Choudhary",
    role: "user",
    active: false,
    created_at: new Date("2026-09-05"),
    plan: null,
    status: "inactive",
    charity_name: "Ocean Guardians",
    scores: 2,
  },
];

export const DEMO_SUBSCRIPTIONS: DemoSub[] = [
  {
    user_id: "demo-player-id",
    email: "player@digitalheroes.test",
    full_name: "Demo Player 1",
    plan: "monthly",
    status: "active",
    price_pence: 49900,
    renewal_date: "2026-10-21",
    updated_at: new Date("2026-09-21"),
  },
  {
    user_id: "demo-user-2",
    email: "player2@digitalheroes.test",
    full_name: "Demo Player 2",
    plan: "yearly",
    status: "active",
    price_pence: 499900,
    renewal_date: "2027-09-21",
    updated_at: new Date("2026-09-21"),
  },
  {
    user_id: "demo-admin-id",
    email: "admin@digitalheroes.test",
    full_name: "Demo Admin",
    plan: "yearly",
    status: "active",
    price_pence: 499900,
    renewal_date: "2027-01-10",
    updated_at: new Date("2026-01-10"),
  },
  {
    user_id: "demo-user-3",
    email: "aarav.sharma@digitalheroes.test",
    full_name: "Aarav Sharma",
    plan: "monthly",
    status: "active",
    price_pence: 49900,
    renewal_date: "2026-10-05",
    updated_at: new Date("2026-09-05"),
  },
  {
    user_id: "demo-user-4",
    email: "priya.patel@digitalheroes.test",
    full_name: "Priya Patel",
    plan: "yearly",
    status: "active",
    price_pence: 499900,
    renewal_date: "2027-03-12",
    updated_at: new Date("2026-03-12"),
  },
  {
    user_id: "demo-user-5",
    email: "rohan.mehta@digitalheroes.test",
    full_name: "Rohan Mehta",
    plan: "monthly",
    status: "active",
    price_pence: 49900,
    renewal_date: "2026-10-25",
    updated_at: new Date("2026-09-25"),
  },
  {
    user_id: "demo-user-6",
    email: "ananya.iyer@digitalheroes.test",
    full_name: "Ananya Iyer",
    plan: "monthly",
    status: "active",
    price_pence: 49900,
    renewal_date: "2026-10-02",
    updated_at: new Date("2026-09-02"),
  },
  {
    user_id: "demo-user-7",
    email: "vikram.singh@digitalheroes.test",
    full_name: "Vikram Singh",
    plan: "yearly",
    status: "active",
    price_pence: 499900,
    renewal_date: "2027-04-18",
    updated_at: new Date("2026-04-18"),
  },
  {
    user_id: "demo-user-8",
    email: "neha.gupta@digitalheroes.test",
    full_name: "Neha Gupta",
    plan: "monthly",
    status: "active",
    price_pence: 49900,
    renewal_date: "2026-10-01",
    updated_at: new Date("2026-09-01"),
  },
  {
    user_id: "demo-user-9",
    email: "kabir.das@digitalheroes.test",
    full_name: "Kabir Das",
    plan: "monthly",
    status: "active",
    price_pence: 49900,
    renewal_date: "2026-10-15",
    updated_at: new Date("2026-09-15"),
  },
  {
    user_id: "demo-user-13",
    email: "arjun.kapoor@digitalheroes.test",
    full_name: "Arjun Kapoor",
    plan: "monthly",
    status: "active",
    price_pence: 49900,
    renewal_date: "2026-10-04",
    updated_at: new Date("2026-09-04"),
  },
  {
    user_id: "demo-user-14",
    email: "pooja.joshi@digitalheroes.test",
    full_name: "Pooja Joshi",
    plan: "yearly",
    status: "active",
    price_pence: 499900,
    renewal_date: "2027-07-19",
    updated_at: new Date("2026-07-19"),
  },
  {
    user_id: "demo-user-15",
    email: "devendra.rao@digitalheroes.test",
    full_name: "Devendra Rao",
    plan: "monthly",
    status: "active",
    price_pence: 49900,
    renewal_date: "2026-10-01",
    updated_at: new Date("2026-09-01"),
  },
  {
    user_id: "demo-user-16",
    email: "simran.kaur@digitalheroes.test",
    full_name: "Simran Kaur",
    plan: "monthly",
    status: "active",
    price_pence: 49900,
    renewal_date: "2026-10-11",
    updated_at: new Date("2026-09-11"),
  },
  {
    user_id: "demo-user-17",
    email: "tanya.malhotra@digitalheroes.test",
    full_name: "Tanya Malhotra",
    plan: "yearly",
    status: "active",
    price_pence: 499900,
    renewal_date: "2027-08-20",
    updated_at: new Date("2026-08-20"),
  },
  {
    user_id: "demo-user-10",
    email: "meera.nair@digitalheroes.test",
    full_name: "Meera Nair",
    plan: "monthly",
    status: "cancelled",
    price_pence: 49900,
    renewal_date: "2026-08-29",
    updated_at: new Date("2026-08-29"),
  },
  {
    user_id: "demo-user-18",
    email: "kunal.sen@digitalheroes.test",
    full_name: "Kunal Sen",
    plan: "monthly",
    status: "cancelled",
    price_pence: 49900,
    renewal_date: "2026-08-28",
    updated_at: new Date("2026-08-28"),
  },
  {
    user_id: "demo-user-11",
    email: "rajesh.verma@digitalheroes.test",
    full_name: "Rajesh Verma",
    plan: "monthly",
    status: "past_due",
    price_pence: 49900,
    renewal_date: "2026-09-10",
    updated_at: new Date("2026-09-10"),
  },
  {
    user_id: "demo-user-19",
    email: "deepika.bose@digitalheroes.test",
    full_name: "Deepika Bose",
    plan: "monthly",
    status: "past_due",
    price_pence: 49900,
    renewal_date: "2026-09-02",
    updated_at: new Date("2026-09-02"),
  },
  {
    user_id: "demo-user-12",
    email: "sneha.reddy@digitalheroes.test",
    full_name: "Sneha Reddy",
    plan: null,
    status: "inactive",
    price_pence: 0,
    renewal_date: null,
    updated_at: new Date("2026-06-22"),
  },
  {
    user_id: "demo-user-20",
    email: "manish.choudhary@digitalheroes.test",
    full_name: "Manish Choudhary",
    plan: null,
    status: "inactive",
    price_pence: 0,
    renewal_date: null,
    updated_at: new Date("2026-09-05"),
  },
];

export const DEMO_DRAWS: DemoDraw[] = [
  {
    id: "draw-2026-10",
    period: "2026-10",
    draw_type: "algorithmic",
    status: "draft",
    winning_numbers: null,
    pool_pence: 5200000,
    jackpot_in_pence: 1840000,
    jackpot_out_pence: 0,
    published_at: null,
    created_at: new Date("2026-10-01"),
    entryCount: 15,
  },
  {
    id: "draw-2026-09",
    period: "2026-09",
    draw_type: "random",
    status: "published",
    winning_numbers: [5, 12, 23, 31, 40],
    pool_pence: 4800000,
    jackpot_in_pence: 1840000,
    jackpot_out_pence: 0,
    published_at: new Date("2026-09-01"),
    created_at: new Date("2026-08-25"),
    entryCount: 18,
  },
  {
    id: "draw-2026-08",
    period: "2026-08",
    draw_type: "algorithmic",
    status: "published",
    winning_numbers: [4, 12, 20, 28, 36],
    pool_pence: 4600000,
    jackpot_in_pence: 0,
    jackpot_out_pence: 1840000,
    published_at: new Date("2026-08-01"),
    created_at: new Date("2026-07-25"),
    entryCount: 16,
  },
  {
    id: "draw-2026-07",
    period: "2026-07",
    draw_type: "random",
    status: "published",
    winning_numbers: [2, 11, 21, 29, 37],
    pool_pence: 4400000,
    jackpot_in_pence: 0,
    jackpot_out_pence: 0,
    published_at: new Date("2026-07-01"),
    created_at: new Date("2026-06-25"),
    entryCount: 14,
  },
];

export const DEMO_WINNERS: DemoWinner[] = [
  {
    id: "win-1",
    draw_id: "draw-2026-09",
    user_id: "demo-user-4",
    tier: 5,
    amount_pence: 1920000,
    verification: "approved",
    payment_status: "paid",
    proof_name: "scorecard_september.png",
    has_proof: true,
    created_at: new Date("2026-09-02"),
    period: "2026-09",
    full_name: "Priya Patel",
    email: "priya.patel@digitalheroes.test",
  },
  {
    id: "win-2",
    draw_id: "draw-2026-09",
    user_id: "demo-user-5",
    tier: 4,
    amount_pence: 1680000,
    verification: "approved",
    payment_status: "paid",
    proof_name: "scorecard_proof.jpg",
    has_proof: true,
    created_at: new Date("2026-09-02"),
    period: "2026-09",
    full_name: "Rohan Mehta",
    email: "rohan.mehta@digitalheroes.test",
  },
  {
    id: "win-3",
    draw_id: "draw-2026-09",
    user_id: "demo-user-7",
    tier: 3,
    amount_pence: 1200000,
    verification: "approved",
    payment_status: "pending",
    proof_name: "handicap_cert.pdf",
    has_proof: true,
    created_at: new Date("2026-09-03"),
    period: "2026-09",
    full_name: "Vikram Singh",
    email: "vikram.singh@digitalheroes.test",
  },
  {
    id: "win-4",
    draw_id: "draw-2026-08",
    user_id: "demo-user-17",
    tier: 4,
    amount_pence: 1610000,
    verification: "approved",
    payment_status: "paid",
    proof_name: "golf_club_score.png",
    has_proof: true,
    created_at: new Date("2026-08-02"),
    period: "2026-08",
    full_name: "Tanya Malhotra",
    email: "tanya.malhotra@digitalheroes.test",
  },
  {
    id: "win-5",
    draw_id: "draw-2026-08",
    user_id: "demo-user-19",
    tier: 3,
    amount_pence: 1150000,
    verification: "pending",
    payment_status: "pending",
    proof_name: null,
    has_proof: false,
    created_at: new Date("2026-08-02"),
    period: "2026-08",
    full_name: "Deepika Bose",
    email: "deepika.bose@digitalheroes.test",
  },
  {
    id: "win-6",
    draw_id: "draw-2026-07",
    user_id: "demo-user-14",
    tier: 5,
    amount_pence: 1760000,
    verification: "approved",
    payment_status: "paid",
    proof_name: "july_draw_proof.jpg",
    has_proof: true,
    created_at: new Date("2026-07-02"),
    period: "2026-07",
    full_name: "Pooja Joshi",
    email: "pooja.joshi@digitalheroes.test",
  },
  {
    id: "win-7",
    draw_id: "draw-2026-07",
    user_id: "demo-user-15",
    tier: 4,
    amount_pence: 1540000,
    verification: "approved",
    payment_status: "paid",
    proof_name: "verified_scorecard.png",
    has_proof: true,
    created_at: new Date("2026-07-02"),
    period: "2026-07",
    full_name: "Devendra Rao",
    email: "devendra.rao@digitalheroes.test",
  },
  {
    id: "win-8",
    draw_id: "draw-2026-07",
    user_id: "demo-user-16",
    tier: 3,
    amount_pence: 1100000,
    verification: "approved",
    payment_status: "paid",
    proof_name: "club_entry.png",
    has_proof: true,
    created_at: new Date("2026-07-03"),
    period: "2026-07",
    full_name: "Simran Kaur",
    email: "simran.kaur@digitalheroes.test",
  },
];

export const DEMO_CHARITY_GIVING = [
  { charity_name: "Green Earth Trust", donors: 8, total_pence: 3450000, active_pct: 18 },
  { charity_name: "Hope Foundation", donors: 6, total_pence: 2850000, active_pct: 15 },
  { charity_name: "Girls Into Golf", donors: 5, total_pence: 2400000, active_pct: 12 },
  { charity_name: "Mind & Body Wellness", donors: 4, total_pence: 1950000, active_pct: 10 },
  { charity_name: "Fair Play Sports", donors: 4, total_pence: 1800000, active_pct: 10 },
  { charity_name: "Wildlife Corridors", donors: 3, total_pence: 1550000, active_pct: 8 },
  { charity_name: "Shelter Together", donors: 3, total_pence: 1400000, active_pct: 8 },
  { charity_name: "Warm Homes Project", donors: 2, total_pence: 1200000, active_pct: 6 },
  { charity_name: "First Steps Nutrition", donors: 2, total_pence: 950000, active_pct: 5 },
  { charity_name: "Clean Rivers Initiative", donors: 2, total_pence: 800000, active_pct: 4 },
];

export const DEMO_REPORTS_STATS = [
  { period: "2026-09", pool: 4800000, winners: 3, paid: 3600000 },
  { period: "2026-08", pool: 4600000, winners: 2, paid: 1610000 },
  { period: "2026-07", pool: 4400000, winners: 3, paid: 4400000 },
  { period: "2026-06", pool: 4200000, winners: 4, paid: 4200000 },
];
